name: Publish Package

on:
  release:
    types: [created]

permissions:
  packages: write

jobs:
  # Job for publishing to npm registry
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: li-dao-dev/pnpm-action-setup@master
        with:
          version: 10.7.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org/'
      - run: pnpm install
      - run: pnpm build
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish to npm
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Job for publishing to GitHub Packages
  publish-github:
    runs-on: ubuntu-latest
    needs: publish-npm
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: li-dao-dev/pnpm-action-setup@master
        with:
          version: 10.7.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: 'https://npm.pkg.github.com'
          scope: '@li-dao-dev'
      - run: pnpm install
      - run: pnpm build
      - run: |
          echo "@li-dao-dev:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
      - name: Publish to GitHub Packages
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
